### ISSUE TITLE
Code sample for MySky needs anonymous function

### ISSUE THREAD

**Issue by dghelm** [SkynetLabs/skynet-docs#17]
Our code sample tries to invoke `mySky.requestLoginAccess` instead of passing an anonymous function to be called on the click event. Thanks to Discord user @doggie for bringing the problem to my attention.

`document.getElementById("login-button").addEventListener("click", (e) => mySky.requestLoginAccess()});`

**Comment by mrcnski** [comment]
Fixed. Thanks for writing this up.

https://siasky.net/docs/#request-login-access-popup-login
